export const selectAccountId = state => state.account.accountID;
export const selectAccountUsername = state => state.account.accountUsername;
export const selectReferralID = state => state.account.referralID;
export const selectTHSpeed = state => state.account.thSpeed;
export const selectTrxRatio = state => state.account.trxRatio;
export const selectTrxValue = state => state.account.trxValue;
export const selectBNBRatio = state => state.account.bnbRatio;
export const selectBNBValue = state => state.account.bnbValue;
export const selectIsBNB = state => state.account.isBnb;